In [11]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import re

In [6]:
billboard = pd.read_csv('hot100.csv')
billboard.columns

C:\Users\Marcel\AppData\Local\Temp\ipykernel_36776\3015988688.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  billboard = pd.read_csv('hot100.csv')

Index(['Date', 'Song', 'Artist', 'Rank', 'Last Week', 'Peak Position',
       'Weeks in Charts', 'Image URL'],
      dtype='object')

In [9]:
billboard.drop(columns=['Image URL'], inplace=True)
billboard.head()

,Date,Song,Artist,Rank,Last Week,Peak Position,Weeks in Charts
0,1958-08-06,Poor Little Fool,Ricky Nelson,1,1,1,2
1,1958-08-06,Nel Blu Dipinto Di Blu (Volare),Domenico Modugno,2,54,2,2
2,1958-08-06,Patricia,Perez Prado And His Orchestra,3,2,2,2
3,1958-08-06,Splish Splash,Bobby Darin,4,3,3,2
4,1958-08-06,When,Kalin Twins,5,5,5,2

In [10]:
spotify = pd.read_csv('dataset-of-10s.csv')
spotify.head()

,track,artist,uri,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
0,Wild Things,Alessia Cara,spotify:track:2ZyuwVvV6Z3XJaXIFbspeE,0.741,0.626,1,-4.826,0,0.0886,0.02000,0.000,0.0828,0.706,108.029,188493,4,41.18681,10,1
1,Surfboard,Esquivel!,spotify:track:61APOtq25SCMuK0V5w2Kgp,0.447,0.247,5,-14.661,0,0.0346,0.87100,0.814,0.0946,0.250,155.489,176880,3,33.18083,9,0
2,Love Someone,Lukas Graham,spotify:track:2JqnpexlO9dmvjUMCaLCLJ,0.550,0.415,9,-6.557,0,0.0520,0.16100,0.000,0.1080,0.274,172.065,205463,4,44.89147,9,1
3,Music To My Ears (feat. Tory Lanez),Keys N Krates,spotify:track:0cjfLhk8WJ3etPTCseKXtk,0.502,0.648,0,-5.698,0,0.0527,0.00513,0.000,0.2040,0.291,91.837,193043,4,29.52521,7,0
4,Juju On That Beat (TZ Anthem),Zay Hilfigerrr & Zayion McCall,spotify:track:1lItf5ZXJc1by9SbPeljFd,0.807,0.887,1,-3.892,1,0.2750,0.00381,0.000,0.3910,0.780,160.517,144244,4,24.99199,8,1

In [22]:
def normalize_title(title):
    title = title.lower()
    title = re.sub(r"\(.*?\)", "", title) #remove text in parentheses
    title = re.sub(r"feat\.|featuring", "", title) #remove 'feat.' or 'featuring' -> can look into it later
    title = re.sub(r'[^a-z0-9\s]', '', title) #delete punctuation
    title = re.sub(r'\s+', ' ', title).strip() #remove extra spaces
    return title

In [23]:
billboard['Normalized Title'] = billboard['Song'].apply(normalize_title)
spotify['Normalized Title'] = spotify['track'].apply(normalize_title)

In [24]:
spotify.head()

,track,artist,uri,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target,Normalized Title
0,Wild Things,Alessia Cara,spotify:track:2ZyuwVvV6Z3XJaXIFbspeE,0.741,0.626,1,-4.826,0,0.0886,0.02000,0.000,0.0828,0.706,108.029,188493,4,41.18681,10,1,wild things
1,Surfboard,Esquivel!,spotify:track:61APOtq25SCMuK0V5w2Kgp,0.447,0.247,5,-14.661,0,0.0346,0.87100,0.814,0.0946,0.250,155.489,176880,3,33.18083,9,0,surfboard
2,Love Someone,Lukas Graham,spotify:track:2JqnpexlO9dmvjUMCaLCLJ,0.550,0.415,9,-6.557,0,0.0520,0.16100,0.000,0.1080,0.274,172.065,205463,4,44.89147,9,1,love someone
3,Music To My Ears (feat. Tory Lanez),Keys N Krates,spotify:track:0cjfLhk8WJ3etPTCseKXtk,0.502,0.648,0,-5.698,0,0.0527,0.00513,0.000,0.2040,0.291,91.837,193043,4,29.52521,7,0,music to my ears
4,Juju On That Beat (TZ Anthem),Zay Hilfigerrr & Zayion McCall,spotify:track:1lItf5ZXJc1by9SbPeljFd,0.807,0.887,1,-3.892,1,0.2750,0.00381,0.000,0.3910,0.780,160.517,144244,4,24.99199,8,1,juju on that beat

In [48]:
merged_data = pd.merge(billboard, spotify, on='Normalized Title', how='inner', suffixes=('_billboard', '_spotify'))

In [51]:
merged_data['Weeks in Charts'] = pd.to_numeric(merged_data['Weeks in Charts'], errors='coerce').astype('Int64')
merged_data['Weeks in Charts'] = merged_data['Weeks in Charts'].fillna(1).astype(int)

In [52]:
#merged_data.head()
#merged_data["Weeks in Charts"] = int(merged_data["Weeks in Charts"])
filtered_data = merged_data[merged_data['Normalized Title'] == 'we are never ever getting back together']
#filtered_data = filtered_data[filtered_data["Weeks in Charts"] < 6]
filtered_data

,Date,Song,Artist,Rank,Last Week,Peak Position,Weeks in Charts,Normalized Title,track,artist,...,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
47378,2012-08-22,We Are Never Ever Getting Back Together,Taylor Swift,72,72,1,1,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
47412,2012-08-29,We Are Never Ever Getting Back Together,Taylor Swift,1,72,1,2,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
47532,2012-09-05,We Are Never Ever Getting Back Together,Taylor Swift,1,1,1,3,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
47654,2012-09-12,We Are Never Ever Getting Back Together,Taylor Swift,2,1,1,4,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
47774,2012-09-19,We Are Never Ever Getting Back Together,Taylor Swift,1,2,1,5,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
47895,2012-09-26,We Are Never Ever Getting Back Together,Taylor Swift,2,1,1,6,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48015,2012-10-03,We Are Never Ever Getting Back Together,Taylor Swift,4,2,1,7,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48139,2012-10-10,We Are Never Ever Getting Back Together,Taylor Swift,4,4,1,8,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48260,2012-10-17,We Are Never Ever Getting Back Together,Taylor Swift,5,4,1,9,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48373,2012-10-24,We Are Never Ever Getting Back Together,Taylor Swift,5,5,1,10,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48487,2012-10-31,We Are Never Ever Getting Back Together,Taylor Swift,4,5,1,11,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48612,2012-11-07,We Are Never Ever Getting Back Together,Taylor Swift,11,4,1,12,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48713,2012-11-14,We Are Never Ever Getting Back Together,Taylor Swift,5,11,1,13,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48829,2012-11-21,We Are Never Ever Getting Back Together,Taylor Swift,7,5,1,14,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
48943,2012-11-28,We Are Never Ever Getting Back Together,Taylor Swift,9,7,1,15,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49059,2012-12-05,We Are Never Ever Getting Back Together,Taylor Swift,11,9,1,16,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49170,2012-12-12,We Are Never Ever Getting Back Together,Taylor Swift,15,11,1,17,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49291,2012-12-19,We Are Never Ever Getting Back Together,Taylor Swift,25,15,1,18,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49405,2012-12-26,We Are Never Ever Getting Back Together,Taylor Swift,27,25,1,19,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49518,2013-01-02,We Are Never Ever Getting Back Together,Taylor Swift,29,27,1,20,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49611,2013-01-09,We Are Never Ever Getting Back Together,Taylor Swift,17,29,1,21,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49730,2013-01-16,We Are Never Ever Getting Back Together,Taylor Swift,25,17,1,22,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49852,2013-01-23,We Are Never Ever Getting Back Together,Taylor Swift,39,25,1,23,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
49971,2013-01-30,We Are Never Ever Getting Back Together,Taylor Swift,46,39,1,24,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1
95466,2021-11-24,We Are Never Ever Getting Back Together (Taylo...,Taylor Swift,55,55,1,1,we are never ever getting back together,We Are Never Ever Getting Back Together,Taylor Swift,...,0.00957,0.000027,0.102,0.75,85.984,191880,4,29.57263,7,1